#!/bin/bash

pipe=/tmp/testpipe

# check pipe 
if [[ ! -p $pipe ]]; then
	echo "reader not running"
	exit 1
fi

# type arg
if [[ "$1" ]]; then
	echo "$1" >$pipe
else
	echo "Hello from $$" >$pipe
fi



